import React from 'react';
import { Link } from 'react-router-dom';
import Header from '../components/Layout/Header';
import Footer from '../components/Layout/Footer';

function HomePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      
      <main className="flex-grow">
        {/* Hero Section */}
        <section className="text-center py-20 sm:py-24 lg:py-32 px-4">
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-light-text dark:text-brand-text tracking-tight">
            Simplify Your Finances.
          </h1>
          <h2 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-accent tracking-tight mt-2">
            Achieve Your Goals.
          </h2>
          <p className="mt-6 max-w-2xl mx-auto text-lg text-light-subtle dark:text-brand-subtle">
            Hisab-Kitab is the all-in-one platform to track expenses, manage budgets, and gain financial clarity with our powerful AI-driven insights.
          </p>
          <div className="mt-8">
            <Link 
              to="/register" 
              className="bg-accent text-white font-bold py-4 px-8 rounded-lg text-lg hover:bg-opacity-90 transition-transform transform hover:scale-105 inline-block"
            >
              Get Started for Free
            </Link>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-20 sm:py-24 bg-light-secondary dark:bg-brand-secondary border-y border-light-tertiary dark:border-brand-tertiary">
          <div className="max-w-6xl mx-auto px-4">
            <div className="text-center mb-12">
              <h2 className="text-3xl lg:text-4xl font-bold text-accent">Powerful Features, Effortless Control</h2>
              <p className="mt-4 text-lg text-light-subtle dark:text-brand-subtle">Everything you need to take command of your financial life.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
              {/* Feature 1 */}
              <div className="bg-light-primary dark:bg-brand-primary p-6 rounded-2xl text-center border border-light-tertiary dark:border-brand-tertiary">
                <div className="text-accent text-4xl mb-4">
                  <i className="fa-solid fa-wallet"></i>
                </div>
                <h3 className="text-xl font-bold mb-2">Smart Tracking</h3>
                <p className="text-light-subtle dark:text-brand-subtle">Easily log every transaction, categorize your spending, and see where your money goes in real-time.</p>
              </div>
              
              {/* Feature 2 */}
              <div className="bg-light-primary dark:bg-brand-primary p-6 rounded-2xl text-center border border-light-tertiary dark:border-brand-tertiary">
                <div className="text-accent text-4xl mb-4">
                  <i className="fa-solid fa-chart-pie"></i>
                </div>
                <h3 className="text-xl font-bold mb-2">Insightful Reports</h3>
                <p className="text-light-subtle dark:text-brand-subtle">Visualize your financial habits with beautiful, easy-to-understand charts and reports.</p>
              </div>
              
              {/* Feature 3 */}
              <div className="bg-light-primary dark:bg-brand-primary p-6 rounded-2xl text-center border border-light-tertiary dark:border-brand-tertiary">
                <div className="text-accent text-4xl mb-4">
                  <i className="fa-solid fa-robot"></i>
                </div>
                <h3 className="text-xl font-bold mb-2">AI Financial Assistant</h3>
                <p className="text-light-subtle dark:text-brand-subtle">Get personalized advice, budget suggestions, and savings plans generated by our smart AI.</p>
              </div>
              
              {/* Feature 4 */}
              <div className="bg-light-primary dark:bg-brand-primary p-6 rounded-2xl text-center border border-light-tertiary dark:border-brand-tertiary">
                <div className="text-accent text-4xl mb-4">
                  <i className="fa-solid fa-lock"></i>
                </div>
                <h3 className="text-xl font-bold mb-2">Secure & Private</h3>
                <p className="text-light-subtle dark:text-brand-subtle">Your data is encrypted and protected. We prioritize your privacy and security above all else.</p>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}

export default HomePage;